# Generated by Django 5.1.1 on 2024-09-12 04:53

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='boshlanish vaqti')),
                ('end_time', models.DateTimeField(verbose_name='tugash vaqti')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.position')),
            ],
        ),
        migrations.CreateModel(
            name='StaffAttandance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('is_come', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
            ],
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('plannet', 'rejalashtirilgan'), ('inprogress', 'in progress'), ('done', 'bajarildi'), ('fail', 'bajarilmadi')], default='plannet', max_length=35)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.staff')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.shift')),
            ],
            options={
                'verbose_name': 'Navbatchilik',
                'verbose_name_plural': 'Navbatchiliklar',
                'unique_together': {('employee', 'shift')},
            },
        ),
    ]
